# Generated by Django 5.0.6 on 2025-07-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('alignment', models.CharField(choices=[('neutral', 'Neutral'), ('friendly', 'Friendly'), ('hostile', 'Hostile')], max_length=20)),
            ],
        ),
    ]
